version: '2'
services:
  api:
     container_name: ecommerce
     image: secret06/nodejs:3.0
     command : pm2 start app.js --no-daemon  --max-memory-restart 3G --merge-logs --log-date-format="YYYY-MM-DD HH:mm Z"
     restart: always
     ports:
      - "8085:8085"
     volumes:
      - .:/app
